spring.datasource.url=jdbc:postgresql://localhost:5432/bank_legacy
spring.datasource.username=matiaszuniga

spring.batch.jdbc.initialize-schema=always

# Job a ejecutar
# Descomentar solo uno antes de iniciar la aplicación.

# spring.batch.job.name=transactionJob
# spring.batch.job.name=interestJob
# spring.batch.job.name=statementJob